baseURL = 'http://example.org/'
languageCode = 'en-us'
title = '50 LLM Projects'
theme = "ananke"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "An exploration of generative AI tools"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"
  recent_posts_number = 3